// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type RefreshToken struct {
	ID           int32
	RefreshToken string
	IsValid      bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Username  string
	Password  string
}
