// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Message struct {
	ID          uuid.UUID
	SenderID    uuid.UUID
	RecipientID uuid.UUID
	Content     string
	CreatedAt   time.Time
	ReadAt      sql.NullTime
	TtlSeconds  sql.NullInt32
	ExpiresAt   sql.NullTime
	Deleted     bool
}

type RefreshToken struct {
	ID           int32
	RefreshToken string
	IsValid      bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	UserID       uuid.UUID
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Username  string
	Password  string
	Email     string
}
